"""Content request generation for wireless edge caching simulations."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from config import SimulationConfig


@dataclass(frozen=True)
class RequestTrace:
    """A sequence of user requests for content files."""

    user_ids: np.ndarray
    file_ids: np.ndarray
    popularity: np.ndarray
    user_activity: np.ndarray


def zipf_probabilities(num_items: int, alpha: float) -> np.ndarray:
    """Return Zipf probabilities for item ranks 1, ..., N."""

    if alpha <= 0:
        return np.ones(num_items, dtype=float) / num_items

    ranks = np.arange(1, num_items + 1, dtype=float)
    weights = 1.0 / (ranks**alpha)
    return weights / np.sum(weights)


def generate_request_trace(
    config: SimulationConfig,
    rng: np.random.Generator,
) -> RequestTrace:
    """Generate a reproducible request trace.

    Content files follow a Zipf distribution, which is commonly used to model
    skewed video or web object popularity. User activity is mildly skewed so
    that demand-aware bandwidth allocation has a clear interpretation.
    """

    popularity = zipf_probabilities(config.num_files, config.zipf_alpha)
    user_activity = zipf_probabilities(config.num_users, config.user_activity_alpha)

    user_ids = rng.choice(
        config.num_users,
        size=config.num_requests,
        p=user_activity,
    )
    file_ids = rng.choice(
        config.num_files,
        size=config.num_requests,
        p=popularity,
    )

    return RequestTrace(
        user_ids=user_ids,
        file_ids=file_ids,
        popularity=popularity,
        user_activity=user_activity,
    )


def file_request_counts(file_ids: np.ndarray, num_files: int) -> np.ndarray:
    """Count how many times each file appears in a request trace."""

    return np.bincount(file_ids, minlength=num_files)


def user_request_counts(user_ids: np.ndarray, num_users: int) -> np.ndarray:
    """Count how many requests are generated by each user."""

    return np.bincount(user_ids, minlength=num_users)
